import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import NavBar from "./NavBar";
import {Theme, ThemePanel} from "@radix-ui/themes"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Issue tracka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={montserrat.variable}>
        <Theme accentColor="pink" radius="small">
          <NavBar />
          <main className="p-5">{children}</main>
          {/* <ThemePanel/> */}
        </Theme>
      </body>
    </html>
  );
}
